Code up the cross entropy RL algorithm for cartpole
Corrected errors (referencing pytorch variables)
Checking in so as to preserve my work

Latest error is:
python3 test2_cartpole.py
/Users/anupkaul/akaul_git/drl/simenvs/cross_entropy/test2_cartpole.py:109: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_new.cpp:264.)
  obs_v = torch.FloatTensor([obs])
Traceback (most recent call last):
  File "/Users/anupkaul/akaul_git/drl/simenvs/cross_entropy/test2_cartpole.py", line 175, in <module>
    for iter_no, batch in enumerate(iterate_batches(env, net, BATCH_SIZE)):
  File "/Users/anupkaul/akaul_git/drl/simenvs/cross_entropy/test2_cartpole.py", line 109, in iterate_batches
    obs_v = torch.FloatTensor([obs])
ValueError: expected sequence of length 4 at dim 2 (got 0)